### PR TITLE
Closest Vector PBC Wrapping

### PR DESCRIPTION
**Pull request by frobnitzem**
Olaf Lenz,

  I've implemented a C plugin that finds the exact closest periodic image for arbitrary box vectors.  The "-parallelepiped" "-orthorhombic" and "-rectangular" options to `pbcwrap` have been replaced by a "-cell" option, which can take "brick/rectangular/orthorhombic" or "parallelepiped" or "compact".  The compact option uses the closest vector search so that all the wrapped points lie in the Voronoi cell.

  I do not know the canonical way to compile C plugins, but I have modified the Makefile to show what worked for me.

Best,
~ David M. Rogers

### CODE REVIEW

**Comment by olenz** [comment]
Hi!

That sounds great. Unfortunately, I am not in science anymore, and I haven't been using VMD since over a year.
Would you be interested to overtake the maintenance of the pbctools package? There is not a lot of maintenance to do, but once in a while, somebody like you adds nice new functionality that would be good to pass on to the VMD guys. The pbctools are bundled with VMD, so it is a good idea to send them the new version.

Olaf

**Comment by frobnitzem** [comment]
Science is like the Hotel California, nobody leaves.  But it sounds like you've found a way to not lose sleep over it anymore.  I have an up-to-date fork, so I can maintain the code on git - no problem, but I'm not a main VMD developer.  I'm checking with them on the update process.

~ David

**Comment by olenz** [comment]
I could also pass the ownership of the repo to you, so that you "inherit" the network. However, you already have a fork of the repo, so I can't.
Also be aware that I have added a note to the repo, that the code is maintained in the main VMD repo, so you should contact them how to maintain the pbctools in the future. Maybe they'll give you write access to their CVS repo... ;-)

I have never been a VMD main developer, so that is no problem.

**Comment by olenz** [comment]
Oh, and concerning science: I have left, and I do not even feel bad about it.

**Comment by frobnitzem** [comment]
Hi Olaf,

   You mentioned that you could not transfer the repository since I had 
a fork.  I've deleted the fork if you want to try transferring again.

Best,
~ David Rogers

**Comment by olenz** [comment]
I have requested the transfer.

**Pull request merged**
